# Generated by Django 4.0.5 on 2023-07-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_vehiculo_condicion_precio_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='condicion_precio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
